pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'mc-settlement-generator'

include 'core-planner'
include 'llm-bridge'
include 'fabric-mod'
