package org.mcsettlement.llm;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

/**
 * Data model for high-level semantic planning intent generated by LLM or Heuristics.
 */
public class PlanningIntent {
    public java.util.List<org.mcsettlement.planner.SettlementPlanner.BuildingRequirement> requirements = new java.util.ArrayList<>();
    public transient int modelCalls;

    /** Single production mapping; no field may disappear in the screen layer. */
    public org.mcsettlement.planner.SettlementPlanner.PlanRequest toPlanRequest(long seed) {
        var request = new org.mcsettlement.planner.SettlementPlanner.PlanRequest();
        request.seed = seed;
        request.targetPlots = targetPlotCount;
        request.roadWidth = roadWidth;
        request.settlementStyle = settlementTheme;
        request.landmarkPlacement = landmarkPlacement;
        if (requirements == null) throw new IllegalArgumentException("requirements must be an array");
        request.requirements = new java.util.ArrayList<>(requirements);
        return request;
    }

    public static String schemaHint() {
        return "Return a JSON object with settlementTheme, roadStyle, paletteTag, targetPlotCount (0..32), " +
                "roadWidth (1..5), landmarkPlacement (ridge|valley|center), loreDescription, and requirements. " +
                "requirements is an array with at most 32 total requested buildings. Each item: " +
                "{id: unique string, purpose: residential|workshop|commercial|government|military|agriculture|industry|culture|mystic, " +
                "count: 1..32, minWidth: 4..32, maxWidth: 4..32, minDepth: 4..32, maxDepth: 4..32, heightLimit: 3..48, " +
                "placement: any|center|ridge|valley|riverbank, maxWaterDistance: 1..32, optional nearPurpose, maxDistance: 1..512}. " +
                "Dimensions are inclusive post-rotation footprint ranges; prefer broad ranges unless the user states exact dimensions. " +
                "Do not output coordinates or individual blocks. Riverbank means on dry land; bridges and climbing roads are unsupported.";
    }

    public static String terrainSummary(org.mcsettlement.planner.terrain.HeightfieldMap map) {
        int min = Integer.MAX_VALUE, max = Integer.MIN_VALUE, water = 0, protectedCells = 0;
        double slope = 0;
        for (int x=0;x<map.getWidth();x++) for(int z=0;z<map.getDepth();z++) {
            int y=map.getLocalSurfaceY(x,z); min=Math.min(min,y); max=Math.max(max,y);
            slope+=map.getLocalSlope(x,z);
            switch(map.getLocalObstacle(x,z)) {
                case WATER, WATER_DEEP -> water++;
                case EXISTING_BUILDING -> protectedCells++;
                default -> { }
            }
        }
        return String.format(java.util.Locale.ROOT,
                "width=%d depth=%d minY=%d maxY=%d waterCells=%d protectedCells=%d meanSlope=%.3f. Available presets: %s",
                map.getWidth(),map.getDepth(),min,max,water,protectedCells,slope/(map.getWidth()*map.getDepth()),
                org.mcsettlement.planner.preset.BuildingPresetRegistry.getInstance().getAllPresets().stream()
                .map(p->p.id+":"+p.category+":"+p.sizeX+"x"+p.sizeZ+"x"+p.sizeY).toList());
    }

    public String settlementTheme = "medieval_rustic";
    public String roadStyle = "gravel_path";
    public String paletteTag = "oak_and_cobblestone";
    public int targetPlotCount = 6;
    public int roadWidth = 3;
    public String landmarkPlacement = "ridge"; // "ridge", "valley", "center"
    public String loreDescription = "A peaceful mountain settlement nestled along the natural ridgelines.";

    public String toJson() {
        return new GsonBuilder().setPrettyPrinting().create().toJson(this);
    }

    public static PlanningIntent fromJson(String json) {
        return new Gson().fromJson(json, PlanningIntent.class);
    }
}
