package org.mcsettlement.llm;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

/**
 * Data model for high-level semantic planning intent generated by LLM or Heuristics.
 */
public class PlanningIntent {
    public String settlementTheme = "medieval_rustic";
    public String roadStyle = "gravel_path";
    public String paletteTag = "oak_and_cobblestone";
    public int targetPlotCount = 6;
    public int roadWidth = 3;
    public String landmarkPlacement = "ridge"; // "ridge", "valley", "center"
    public String loreDescription = "A peaceful mountain settlement nestled along the natural ridgelines.";

    public String toJson() {
        return new GsonBuilder().setPrettyPrinting().create().toJson(this);
    }

    public static PlanningIntent fromJson(String json) {
        return new Gson().fromJson(json, PlanningIntent.class);
    }
}
